const screenIds=['01','06','08','12']; let current=0, wheelLock=false;
function showScreen(id,updateHash=true){const idx=screenIds.indexOf(id); if(idx<0)return; current=idx; document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===id)); document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id)); if(updateHash) history.replaceState(null,'','#'+id)}
function fitStage(){const s=document.getElementById('stage'); const scale=Math.min(innerWidth/1920,innerHeight/1080); s.style.transform=`scale(${scale})`; document.body.style.background=getComputedStyle(document.querySelector('.screen.active')).backgroundColor||'#0b1412'}
window.addEventListener('resize',fitStage); window.addEventListener('load',()=>{const h=location.hash.replace('#',''); if(screenIds.includes(h))showScreen(h,false); fitStage()});
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.go)));
window.addEventListener('keydown',e=>{if(['ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();showScreen(screenIds[Math.min(current+1,screenIds.length-1)])} if(['ArrowUp','PageUp'].includes(e.key)){e.preventDefault();showScreen(screenIds[Math.max(current-1,0)])}});
window.addEventListener('wheel',e=>{if(wheelLock)return; wheelLock=true; showScreen(screenIds[Math.max(0,Math.min(screenIds.length-1,current+(e.deltaY>0?1:-1)))]); setTimeout(()=>wheelLock=false,650)},{passive:true});
const tabBtns=[...document.querySelectorAll('#s08 [data-tab]')]; tabBtns.forEach(btn=>btn.addEventListener('click',()=>{tabBtns.forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('#s08 [data-panel]').forEach(p=>p.classList.toggle('active',p.dataset.panel===btn.dataset.tab))}));
const levelBtns=[...document.querySelectorAll('#s08 [data-level]')]; levelBtns.forEach(btn=>btn.addEventListener('click',()=>{levelBtns.forEach(b=>b.classList.remove('active'));btn.classList.add('active');const badge=document.getElementById('opcBadge');badge.textContent=btn.dataset.level+' OPC';badge.style.background=btn.dataset.level==='高级'?'#f0e5ce':'#e0f2e9';badge.style.color=btn.dataset.level==='高级'?'#84642d':'#29634f'}));
const stageData={
1:{k:'MILESTONE 01',t:'项目立项',d:'完成时间：9月20日（示意）',tasks:['确认项目目标','明确项目成员','确认交付边界'],deliver:'项目任务书 V1.0',status:'已确认',act:'项目动态：项目已完成立项，明确参与角色、周期和交付边界。'},
2:{k:'MILESTONE 02',t:'需求确认',d:'完成时间：9月25日（示意）',tasks:['企业需求访谈','业务范围确认','验收口径确认'],deliver:'需求确认单 V1.0',status:'已确认',act:'项目动态：企业需求已完成标准化，交付范围和验收口径已确认。'},
3:{k:'MILESTONE 03',t:'数据整理',d:'完成时间：10月05日（示意）',tasks:['资料收集','数据分类','敏感信息检查'],deliver:'资料清洗清单 V1.0',status:'已完成',act:'项目动态：资料已完成分类与清洗，进入知识库构建准备阶段。'},
4:{k:'MILESTONE 04',t:'知识库系统建设',d:'完成时间：10月18日（示意）',tasks:['知识文档清洗','RAG检索调优','问答效果测试'],deliver:'知识库 Beta V0.8',status:'等待企业确认',act:'项目动态：已完成核心资料入库，当前进入检索调优与问答效果测试阶段。'},
5:{k:'MILESTONE 05',t:'测试验收',d:'计划时间：10月25日（示意）',tasks:['业务场景测试','问题修正','验收材料准备'],deliver:'验收版本 V1.0',status:'待开始',act:'项目动态：将在系统建设确认后进入测试与企业验收。'},
6:{k:'MILESTONE 06',t:'项目归档',d:'计划时间：10月28日（示意）',tasks:['交付资料归档','企业评价','人才履历沉淀'],deliver:'项目归档包',status:'待开始',act:'项目动态：项目验收后将沉淀项目案例、企业评价和人才真实履历。'}
};
document.querySelectorAll('.stage-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.stage-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const x=stageData[btn.dataset.stage];document.getElementById('stageKicker').textContent=x.k;document.getElementById('stageTitle').textContent=x.t;document.getElementById('stageDue').textContent=x.d;document.getElementById('task1').textContent=x.tasks[0];document.getElementById('task2').textContent=x.tasks[1];document.getElementById('task3').textContent=x.tasks[2];document.getElementById('deliverName').textContent=x.deliver;document.getElementById('deliverStatus').textContent=x.status;document.getElementById('activityText').textContent=x.act;}));